- hosts: all
  become: yes
  tasks:
    - name: apt update and install generic tools I always need
      apt:
        name: "{{ item }}"
        update_cache: yes
      loop:
        - htop
        - nano
        - iftop
        - bind9-dnsutils
        - tcpdump
        - unzip
        - gzip
        - net-tools
        - mtr-tiny
        - iptables-persistent
        - tldr